### ISSUE TITLE
Local환경 이미지 api 동작 x

### ISSUE THREAD

**Issue by EJKim3191** [NadeulSeoulTeam/NadeulSeoul_front_end#58]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/95759697/170864413-16860704-7db5-4d55-95d0-66774ca4db26.png">

1. 서버 내부의 디렉토리에 이미지를 저장하는 방식
2. 타 서버에 저장 후 url을 보내주는 방식

2가지의 경우 중 어떤 방식인가요?

**Comment by yoonnotyoun** [comment]
@nesllewr @dgh03207

**Comment by dgh03207** [comment]
서버 디렉토리에 저장하는 방식입니다
