### ISSUE TITLE
following 처음 접속했을 때 팔로우 버튼 상태 오류

### ISSUE THREAD

**Issue by yoonnotyoun** [NadeulSeoulTeam/NadeulSeoul_front_end#72]
navbar 통해 팔로잉 목록 들어가면 내가 팔로우 하고 있는 사람들 목록임에도 언팔로우 버튼이 아니라 팔로우 버튼으로 뜸
팔로워 리스트 갔다가 다시 팔로잉 리스트로 돌아오면 정상적으로 뜸
오직 처음 들어갔을 때만 오류 나는 것으로 보임

**Comment by joojeehwan** [comment]
고침
